import './globals.css';
import '@/env/server-env';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { ClientSideProviders } from './providers';
import { localeSchema } from '@/types/locale';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = async ({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) => {
  const paramLocale = await params.then(p => p.locale);
  const localeResult = localeSchema.safeParse(paramLocale);
  if (!localeResult.success) {
    notFound();
  }
  const locale = localeResult.data;
  const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <NextIntlClientProvider messages={messages}>
          <ClientSideProviders>{children}</ClientSideProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
export default RootLayout;
